- name: Configure the jenkins slave  ec2 with the required Packages
  hosts: slave
  become: yes
  tasks:
   - name: update Packages
     apt:
      update_cache: yes

   - name: upgrad all Packages
     apt:
      upgrade: yes

   - name: Create Jenkins directory
     ansible.builtin.file:
      path: "Jenkins_home"
      state: directory
      mode: '0777'
      
   - name: install OpedJDK 17
     apt:
      name: openjdk-17-jdk
      state: present

        # install docker 

   - name: Remove existing Docker packages
     apt:
        name: "{{ item }}"
        state: absent
     with_items:
        - docker
        - docker-engine
        - docker.io
        - containerd
        - runc

   - name: Install required packages
     apt:
        name: "{{ item }}"
        state: present
     with_items:
        - ca-certificates
        - curl
        - gnupg
        - lsb-release

   - name: Create Docker GPG keyring directory
     file:
        path: /etc/apt/keyrings
        state: directory

   - name: Download and install Docker GPG key
     shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg

   - name: Add Docker repository
     copy:
        content: |
          deb [arch={{ dpkg_architecture }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ lsb_release_codename }} stable
        dest: /etc/apt/sources.list.d/docker.list
        mode: '0644'

   - name: Update package lists
     apt:
        update_cache: yes

   - name: Install Docker
     apt:
        name: "{{ item }}"
        state: present
     with_items:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose


    